#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in7,    clawPot,        sensorNone)
#pragma config(Sensor, in8,    arm,            sensorNone)
#pragma config(Sensor, dgtl1,  shaft1,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  shaft2,         sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightLift1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftLift2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightLift2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]


task main()
{
while(1==1){
    clearLCDLine(0);
    clearLCDLine(1);
		displayLCDNumber(0, 0, SensorValue(arm), 5);
  	displayLCDNumber(1, 0, SensorValue(clawPot), 5);
		//holonomic drive code
  	if (C1LX < 10)
  		C1LX = 0;
  	if (C1LY < 10)
  		C1LY = 0;
  	if (C1RX < 10)
  		C1RX = 0;
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		//Lift go up
		if(VexRT[Btn6U] && sensorValue(arm) < 2700){
			motor[RightLift1] = 127;
			motor[RightLift2] = 127;
			motor[LeftLift1] = 127;
			motor[LeftLift2] = 127;
		}
		//Lift go down
		else if (VexRT[Btn6D]&& sensorValue(arm) > 0){
			motor[RightLift1] = -127;
			motor[RightLift2] = -127;
			motor[LeftLift1] = -127;
			motor[LeftLift2] = -127;
		}
		//Do nothing (run off)
		else{
			motor[RightLift1] = 0;
			motor[RightLift2] = 0;
			motor[LeftLift1] = 0;
			motor[LeftLift2] = 0;
		}

		//Opens claw
		if(VexRT[Btn5U] && sensorValue(claw) < 750){
			motor[claw] = -127;
    	motor[claw2] = -127;
		}
		else if(VexRT[Btn8D]){
			motor[claw] = -127;
    	motor[claw2] = -127;
		}
		//closes claw
		else if(VexRT[Btn5D]&& sensorValue(claw) > 200){
			motor[claw] = 127;
    	motor[claw2] = 127;
		}
		//Do nothing
		else{
			motor[claw] = 0;
			motor[claw2] = 0;
		}

}
}
